/**
 * Utilitaire pour nettoyer le texte généré par IA
 * Supprime les artefacts JSON/échappement indésirables
 */

import { applyFrenchTypography } from './frenchTypography';

/**
 * Nettoie le texte généré pour supprimer les artefacts d'échappement JSON
 * @param text Le texte à nettoyer
 * @returns Le texte nettoyé
 */
export function cleanGeneratedText(text: string): string {
  if (!text || typeof text !== 'string') return text || '';
  
  let cleaned = text
    // ========== NETTOYAGE MARKDOWN / ASTÉRISQUES ==========
    // Supprimer gras+italique ***text*** ou ___text___
    .replace(/\*{3}(.+?)\*{3}/g, '$1')
    .replace(/_{3}(.+?)_{3}/g, '$1')
    // Supprimer gras **text** ou __text__
    .replace(/\*{2}(.+?)\*{2}/g, '$1')
    .replace(/_{2}(.+?)_{2}/g, '$1')
    // Supprimer italique *text* ou _text_ (pas les underscores dans les mots)
    .replace(/\*(.+?)\*/g, '$1')
    // Supprimer les astérisques orphelins restants
    .replace(/\*+/g, '')
    // Supprimer les titres markdown # ## ### etc.
    .replace(/^#{1,6}\s+/gm, '')
    // Supprimer les séparateurs markdown --- *** ===
    .replace(/^[=\-*_]{3,}\s*$/gm, '')
    // Supprimer les balises de liste markdown - ou *
    .replace(/^\s*[-*]\s+/gm, '• ')
    // ========== NETTOYAGE DES ENTITÉS HTML ==========
    .replace(/&nbsp;?/gi, ' ')
    .replace(/&#160;/gi, ' ')
    .replace(/&#xa0;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&apos;/gi, "'")
    .replace(/&#39;/gi, "'")
    // Convertir les guillemets échappés \" -> guillemet réel
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '')
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    .replace(/\\\//g, '/')
    // Supprimer les patterns JSON résiduels
    .replace(/^\s*{\s*"[^"]*"\s*:\s*"/gm, '')
    .replace(/"\s*}\s*$/gm, '')
    .replace(/^\s*\[\s*"/gm, '')
    .replace(/"\s*\]\s*$/gm, '')
    .replace(/",\s*"[^"]*"\s*:\s*"/g, ' ')
    .replace(/":\s*"/g, ': ')
    .replace(/{\s*"/g, '')
    .replace(/"\s*}/g, '')
    // Supprimer les fragments JSON qui fuient dans le texte
    // Cas exact: jsonnumero": 3, " titre:  ou  json"numero": 3, "
    .replace(/json\s*"?\s*numero\s*"?\s*:\s*\d+\s*,?\s*"?\s*(titre)?\s*"?\s*:?\s*/gi, '')
    // Cas: "numero": 3, "titre":  ou numero": 3, "
    .replace(/"?\s*numero\s*"?\s*:\s*\d+\s*,?\s*"?\s*(titre)?\s*"?\s*:?\s*/gi, '')
    // Cas génériques de clés JSON orphelines
    .replace(/(^|\s)"?(titre|title|content|chapters|subChapters|contenu|numero)"?\s*:\s*/gi, '$1')
    .replace(/^[\[{,\s]+"?(numero|titre|title|content|chapters|subChapters|contenu)"?\s*:\s*/gim, '')
    .replace(/^"{3,}/gm, '"')
    .replace(/"{3,}$/gm, '"')
    // ========== NETTOYAGE DES MÉTADONNÉES / ARTEFACTS DE STATS ==========
    // Supprimer les lignes de stats "Nombre de mots : 1234" ou "Nombre de mots = 1234"
    .replace(/\b(?:nombre\s+de\s+mots|word\s*count|mots?\s*:?\s*total)\s*[:=]\s*\d[\d\s.,]*/gi, '')
    // Supprimer "Export EPUB natif" et variantes + toute la phrase qui suit
    .replace(/export\s+epub\s*(?:natif|native)?[^.\n]*/gi, '')
    // Supprimer "Pages estimées : 123" ou "Estimated pages: 123"
    .replace(/\b(?:pages?\s+estim[ée]e?s?|estimated\s+pages?)\s*[:=]\s*\d[\d\s.,]*/gi, '')
    // Supprimer "Chapitre X - Nombre de mots : Y"
    .replace(/chapitre\s+\d+\s*[-–—]\s*nombre\s+de\s+mots\s*[:=]\s*\d[\d\s.,]*/gi, '')
    // Supprimer les lignes "Score :" "Lisibilité :" etc. isolées avec un nombre
    .replace(/\b(?:score|lisibilit[ée]|readability|flesch)\s*[:=]\s*\d[\d.,]*\s*(?:\/\s*\d+)?/gi, '')
    // Supprimer les annotations IA résiduelles type "[Note: ...]" ou "(Note de l'auteur: ...)"
    .replace(/\[(?:note|remarque|ndlr|instruction|info|warning|tip|important)[^\]]*\]/gi, '')
    .replace(/\((?:note\s+de\s+l'auteur|note\s+de\s+l'éditeur|note\s*:)[^)]*\)/gi, '')
    // Supprimer les compteurs de mots en fin de section "~1500 mots" ou "(2000 mots)"
    .replace(/[~≈]?\s*\d{3,5}\s*mots?\b/gi, '')
    .replace(/\(\s*\d{3,5}\s*mots?\s*\)/gi, '')
    // ========== NETTOYAGE ARTEFACTS IA COURANTS ==========
    // Supprimer "Généré par IA" / "Generated by AI" / "Créé avec..." etc.
    .replace(/\b(?:g[ée]n[ée]r[ée]\s+par\s+(?:ia|ai|intelligence\s+artificielle)|generated\s+by\s+ai|cr[ée][ée]\s+avec\s+(?:ia|ai|chatgpt|gemini|claude))[^.\n]*/gi, '')
    // Supprimer "Fin du chapitre" / "End of chapter" en fin de texte
    .replace(/\n\s*[-–—]*\s*(?:fin\s+du\s+chapitre|end\s+of\s+chapter|fin\s+de\s+(?:la\s+)?section)\s*[-–—]*\s*$/gi, '')
    // Supprimer les phrases-instructions IA résiduelles
    .replace(/\b(?:voici|here\s+is|ci-dessous|below\s+is)\s+(?:le|la|les|the|your|un|une)\s+(?:chapitre|chapter|texte|text|contenu|content|version)[^.\n]*[.:]\s*/gi, '')
    // Supprimer "Ce chapitre contient X mots" et variantes
    .replace(/\b(?:ce\s+chapitre|this\s+chapter|cette\s+section)\s+(?:contient|contains|fait|compte)\s+[^.\n]*\d+\s*mots?[^.\n]*/gi, '')
    // Supprimer les métadonnées de format "Format : X" "Longueur : Y"
    .replace(/\b(?:format|longueur|length|tokens?|caractères|characters)\s*[:=]\s*[^\n]*/gi, '')
    // Supprimer les blocs "---" ou "***" utilisés comme séparateurs IA
    .replace(/^\s*(?:---+|\*\*\*+|===+|___+)\s*$/gm, '')
    // Supprimer "Résumé :" ou "Summary :" en début de paragraphe (artefact IA)
    .replace(/^(?:résumé|summary|synopsis|abstract)\s*[:]\s*/gim, '')
    // Supprimer les lignes vides avec seulement des tirets/astérisques
    .replace(/^\s*[-*=_]{1,2}\s*$/gm, '')
    .replace(/  +/g, ' ')
    .replace(/ ([.,;:!?])/g, '$1');
  
  // ✅ CRITIQUE: Boucle RENFORCÉE pour garantir que TOUS les mots collés sont corrigés
  // Augmenté à 10 itérations pour couvrir tous les cas complexes
  let previousLength = 0;
  let iterations = 0;
  const maxIterations = 10;
  
  while (cleaned.length !== previousLength && iterations < maxIterations) {
    previousLength = cleaned.length;
    iterations++;
    
    cleaned = cleaned
      // ========== CAS 1: PONCTUATION FORTE + LETTRE ==========
      // Point suivi d'une lettre (minuscule ou majuscule, y compris accents)
      .replace(/\.([A-Za-zÀ-ÖØ-öø-ÿ])/g, '. $1')
      // Exclamation suivie d'une lettre
      .replace(/!([A-Za-zÀ-ÖØ-öø-ÿ])/g, '! $1')
      // Interrogation suivie d'une lettre
      .replace(/\?([A-Za-zÀ-ÖØ-öø-ÿ])/g, '? $1')
      // Points de suspension suivis d'une lettre
      .replace(/…([A-Za-zÀ-ÖØ-öø-ÿ])/g, '… $1')
      // Trois points consécutifs suivis d'une lettre
      .replace(/\.\.\.([A-Za-zÀ-ÖØ-öø-ÿ])/g, '... $1')
      
      // ========== CAS 2: PONCTUATION FAIBLE + LETTRE ==========
      // Virgule suivie d'une lettre
      .replace(/,([A-Za-zÀ-ÖØ-öø-ÿ])/g, ', $1')
      // Point-virgule suivi d'une lettre
      .replace(/;([A-Za-zÀ-ÖØ-öø-ÿ])/g, '; $1')
      // Deux-points suivis d'une lettre (IMPORTANT pour les dialogues)
      .replace(/:([A-Za-zÀ-ÖØ-öø-ÿ])/g, ': $1')
      
      // ========== CAS 3: PONCTUATION + CHIFFRE ==========
      .replace(/\.(\d)/g, '. $1')
      .replace(/,(\d)/g, ', $1')
      .replace(/:(\d)/g, ': $1')
      .replace(/!(\d)/g, '! $1')
      .replace(/\?(\d)/g, '? $1')
      
      // ========== CAS 4: GUILLEMETS FRANÇAIS ==========
      // Après guillemet fermant français suivi d'une lettre
      .replace(/»([A-Za-zÀ-ÖØ-öø-ÿ])/g, '» $1')
      // Ponctuation + guillemet fermant + lettre
      .replace(/\.»([A-Za-zÀ-ÖØ-öø-ÿ])/g, '.» $1')
      .replace(/!»([A-Za-zÀ-ÖØ-öø-ÿ])/g, '!» $1')
      .replace(/\?»([A-Za-zÀ-ÖØ-öø-ÿ])/g, '?» $1')
      
      // ========== CAS 5: GUILLEMETS ANGLAIS ==========
      // Après guillemet fermant anglais suivi d'une lettre
      .replace(/"([A-Za-zÀ-ÖØ-öø-ÿ])/g, '" $1')
      // Ponctuation + guillemet fermant + lettre
      .replace(/\."([A-Za-zÀ-ÖØ-öø-ÿ])/g, '." $1')
      .replace(/!"([A-Za-zÀ-ÖØ-öø-ÿ])/g, '!" $1')
      .replace(/\?"([A-Za-zÀ-ÖØ-öø-ÿ])/g, '?" $1')
      
      // ========== CAS 6: PARENTHÈSES ==========
      // Après parenthèse fermante suivie d'une lettre
      .replace(/\)([A-Za-zÀ-ÖØ-öø-ÿ])/g, ') $1')
      // Ponctuation + parenthèse fermante + lettre
      .replace(/\.\)([A-Za-zÀ-ÖØ-öø-ÿ])/g, '.) $1')
      
      // ========== CAS 7: CROCHETS ==========
      .replace(/\]([A-Za-zÀ-ÖØ-öø-ÿ])/g, '] $1')
      
      // ========== CAS 8: TIRETS LONGS (dialogues) ==========
      // Tiret long suivi d'une lettre sans espace
      .replace(/—([A-Za-zÀ-ÖØ-öø-ÿ])/g, '— $1')
      .replace(/–([A-Za-zÀ-ÖØ-öø-ÿ])/g, '– $1');
  }
  
  // Nettoyage final
  cleaned = cleaned
    // Supprimer les caractères de contrôle Unicode indésirables (SAUF \n et \t)
    .replace(/[\u0000-\u0009\u000B\u000C\u000E-\u001F\u007F-\u009F]/g, '')
    // Nettoyer les doubles espaces (réapparus après corrections)
    .replace(/  +/g, ' ')
    // Nettoyer les lignes vides multiples
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return cleaned;
}

/**
 * Nettoie le texte ET applique la typographie française professionnelle.
 * À utiliser pour les exports (DOCX, EPUB, PDF).
 */
export function cleanAndTypographize(text: string): string {
  const cleaned = cleanGeneratedText(text);
  return applyFrenchTypography(cleaned);
}

/**
 * Nettoie un chapitre entier (titre et contenu)
 * @param chapter L'objet chapitre à nettoyer
 * @returns Le chapitre avec le texte nettoyé
 */
export function cleanChapter<T extends { titre?: string; title?: string; contenu?: string; content?: string }>(chapter: T): T {
  if (!chapter) return chapter;
  
  return {
    ...chapter,
    titre: chapter.titre ? cleanGeneratedText(chapter.titre) : chapter.titre,
    title: chapter.title ? cleanGeneratedText(chapter.title) : chapter.title,
    contenu: chapter.contenu ? cleanGeneratedText(chapter.contenu) : chapter.contenu,
    content: chapter.content ? cleanGeneratedText(chapter.content) : chapter.content,
  };
}

/**
 * Nettoie un tableau de chapitres
 * @param chapters Tableau de chapitres à nettoyer
 * @returns Tableau de chapitres avec le texte nettoyé
 */
export function cleanChapters<T extends { titre?: string; title?: string; contenu?: string; content?: string }>(chapters: T[]): T[] {
  if (!chapters || !Array.isArray(chapters)) return chapters || [];
  return chapters.map(cleanChapter);
}

/**
 * Compte le nombre de "mots collés" (ponctuation suivie directement d'une lettre/chiffre)
 * @param text Le texte à analyser
 * @returns Le nombre de mots collés détectés
 */
export function countStuckWords(text: string): number {
  if (!text || typeof text !== 'string') return 0;
  
  // Pattern pour détecter les mots collés après ponctuation
  const stuckWordsPattern = /([.!?…,;:])(?=[A-ZÀ-ÖØ-öø-ÿa-z0-9])/g;
  const matches = text.match(stuckWordsPattern);
  
  return matches ? matches.length : 0;
}

/**
 * Compte les mots collés dans tout le contenu d'un livre
 * @param chapters Tableau de chapitres
 * @param preface Préface du livre
 * @param conclusion Conclusion du livre
 * @returns Le nombre total de mots collés
 */
export function countAllStuckWords(
  chapters: Array<{ title?: string; content?: string; subChapters?: Array<{ title?: string; content?: string }> }>,
  preface: string = '',
  conclusion: string = ''
): number {
  let total = 0;
  
  // Compter dans la préface et conclusion
  total += countStuckWords(preface);
  total += countStuckWords(conclusion);
  
  // Compter dans chaque chapitre
  for (const chapter of chapters) {
    total += countStuckWords(chapter.title || '');
    total += countStuckWords(chapter.content || '');
    
    // Compter dans les sous-chapitres
    if (chapter.subChapters) {
      for (const sub of chapter.subChapters) {
        total += countStuckWords(sub.title || '');
        total += countStuckWords(sub.content || '');
      }
    }
  }
  
  return total;
}

/**
 * Nettoie le texte spécifiquement pour la synthèse vocale (TTS).
 * Supprime tout le markdown, les astérisques, les balises, et optimise pour la lecture audio.
 */
export function cleanForAudio(text: string): string {
  if (!text || typeof text !== 'string') return text || '';
  
  let cleaned = cleanGeneratedText(text);
  
  cleaned = cleaned
    // Supprimer TOUT astérisque restant (gras, italique, orphelins)
    .replace(/\*/g, '')
    // Supprimer underscores de mise en forme
    .replace(/_([^_]+)_/g, '$1')
    .replace(/_+/g, ' ')
    // Supprimer les titres markdown # ## ### etc.
    .replace(/^#{1,6}\s*/gm, '')
    // Supprimer les balises HTML résiduelles
    .replace(/<[^>]*>/g, '')
    // Supprimer les crochets markdown [texte](url)
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    // Supprimer les crochets simples [texte]
    .replace(/\[([^\]]*)\]/g, '$1')
    // Supprimer les backticks
    .replace(/`+/g, '')
    // ========== NETTOYAGE DES MÉTADONNÉES AUDIO ==========
    // Supprimer "Nombre de mots : 1234", "Export EPUB natif", compteurs etc.
    .replace(/\b(?:nombre\s+de\s+mots|word\s*count|mots?\s*:?\s*total)\s*[:=]\s*\d[\d\s.,]*/gi, '')
    .replace(/export\s+epub\s*(?:natif|native)?[^.\n]*/gi, '')
    .replace(/\b(?:pages?\s+estim[ée]e?s?|estimated\s+pages?)\s*[:=]\s*\d[\d\s.,]*/gi, '')
    .replace(/[~≈]?\s*\d{3,5}\s*mots?\b/gi, '')
    .replace(/\(\s*\d{3,5}\s*mots?\s*\)/gi, '')
    .replace(/\[(?:note|remarque|ndlr|instruction)[^\]]*\]/gi, '')
    // Remplacer les puces par des pauses naturelles
    .replace(/^•\s*/gm, '')
    .replace(/^[-–—]\s+/gm, '')
    // Supprimer les numéros de liste (1. 2. etc.) en début de ligne
    .replace(/^\d+\.\s+/gm, '')
    // Ajouter des pauses naturelles (points de suspension → pause)
    .replace(/\.{3,}/g, '...')
    // Supprimer les doubles tirets
    .replace(/--+/g, ', ')
    // Supprimer les séparateurs markdown --- *** ===
    .replace(/^[=\-*_]{3,}\s*$/gm, '')
    // Supprimer les emojis (blocs Unicode emoji)
    .replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{200D}\u{20E3}\u{E0020}-\u{E007F}]/gu, '')
    // Convertir les abréviations courantes pour la lecture
    .replace(/\bn°\s*/gi, 'numéro ')
    .replace(/\bM\.\s/g, 'Monsieur ')
    .replace(/\bMme\s/g, 'Madame ')
    .replace(/\bDr\.\s/g, 'Docteur ')
    .replace(/\betc\.\s/g, 'et cætera. ')
    .replace(/\bcf\.\s/gi, 'voir ')
    .replace(/\bex\.\s/gi, 'par exemple ')
    // Améliorer la ponctuation pour des pauses naturelles
    .replace(/\s*;\s*/g, '. ')
    .replace(/\s*:\s*$/gm, '.')
    // Nettoyer les lignes vides multiples
    .replace(/\n{3,}/g, '\n\n')
    // Nettoyer les espaces multiples
    .replace(/  +/g, ' ')
    .trim();
  
  // POST-PROCESSING DE FORCE : boucle pour garantir zéro artefact
  let prev = '';
  let iterations = 0;
  while (cleaned !== prev && iterations < 5) {
    prev = cleaned;
    iterations++;
    cleaned = cleaned
      .replace(/\*/g, '')
      .replace(/#/g, '')
      .replace(/`/g, '')
      .replace(/^_+|_+$/gm, '')
      .replace(/  +/g, ' ');
  }
  
  return cleaned;
}

/**
 * Détecte les caractères spéciaux markdown interdits dans un texte audio.
 * Retourne un objet avec le nombre d'artefacts et les types trouvés.
 */
export function detectAudioArtifacts(text: string): { count: number; types: string[] } {
  if (!text || typeof text !== 'string') return { count: 0, types: [] };
  
  const checks: Array<{ pattern: RegExp; label: string }> = [
    { pattern: /\*+/g, label: 'Astérisques (*)' },
    { pattern: /#{1,6}\s/g, label: 'Titres markdown (#)' },
    { pattern: /`+/g, label: 'Backticks (`)' },
    { pattern: /__+/g, label: 'Underscores doubles (__)' },
    { pattern: /^[-–—]{3,}\s*$/gm, label: 'Séparateurs (---)' },
    { pattern: /<[^>]+>/g, label: 'Balises HTML' },
  ];
  
  let count = 0;
  const types: string[] = [];
  
  for (const { pattern, label } of checks) {
    const matches = text.match(pattern);
    if (matches && matches.length > 0) {
      count += matches.length;
      types.push(`${label} (×${matches.length})`);
    }
  }
  
  return { count, types };
}
