import type { LucideIcon } from 'lucide-react';
import {
  Target,
  TrendingUp,
  Layers,
  FileText,
  Sparkles,
  CheckCircle2,
  BookOpen,
  AlertCircle,
  Brain,
  Link2,
  ScanSearch,
  Wand2,
  Award,
  BadgeCheck,
  Shield,
} from 'lucide-react';

export interface WorkflowStepDefinition {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  agentTitle: string;
  agentSubtitle: string;
  agentMission: string;
  agentRole: string;
  agentAction: string;
}

export const WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  {
    id: 'P1',
    name: "L'Éditeur",
    description: 'Vision stratégique et analyse du projet',
    icon: Target,
    agentTitle: "Agent 1 — L'Éditeur",
    agentSubtitle: 'Directeur Éditorial',
    agentMission: 'Clarifie la promesse, le ton et l\'angle commercial du livre avant toute production.',
    agentRole: 'Cadrer le manuscrit',
    agentAction: 'Vision stratégique et analyse du projet',
  },
  {
    id: 'P2',
    name: 'Le Marché',
    description: 'Positionnement Amazon KDP + 7 mots-clés stratégiques',
    icon: TrendingUp,
    agentTitle: "Agent 2 — Le Marché",
    agentSubtitle: 'Analyse de Marché',
    agentMission: 'Détecte le positionnement, les catégories et les mots-clés à potentiel.',
    agentRole: 'Valider la niche',
    agentAction: 'Positionnement Amazon KDP + 7 mots-clés stratégiques',
  },
  {
    id: 'P3',
    name: "L'Architecte",
    description: 'Structure détaillée (400+ pages)',
    icon: Layers,
    agentTitle: "Agent 3 — L'Architecte",
    agentSubtitle: 'Architecte de Contenu',
    agentMission: 'Construit un plan exploitable, solide, cohérent et prêt pour la rédaction.',
    agentRole: 'Dessiner la structure',
    agentAction: 'Structure détaillée (400+ pages)',
  },
  {
    id: 'P4',
    name: 'Le Romancier',
    description: 'Écriture professionnelle chapitre par chapitre',
    icon: FileText,
    agentTitle: "Agent 4 — Le Romancier",
    agentSubtitle: 'Rédaction Experte',
    agentMission: 'Produit le manuscrit chapitre par chapitre avec continuité narrative et densité utile.',
    agentRole: 'Rédiger les chapitres',
    agentAction: 'Écriture professionnelle chapitre par chapitre',
  },
  {
    id: 'P5',
    name: 'Le Styliste',
    description: 'Humanisation du texte (votre voix, pas un robot)',
    icon: Sparkles,
    agentTitle: "Agent 5 — Le Styliste",
    agentSubtitle: 'Réécriture Naturelle',
    agentMission: 'Supprime les tournures mécaniques et rend la prose plus naturelle et crédible.',
    agentRole: 'Humaniser le ton',
    agentAction: 'Humanisation du texte (votre voix, pas un robot)',
  },
  {
    id: 'P6',
    name: 'Le Correcteur',
    description: 'Contrôle qualité approfondi',
    icon: CheckCircle2,
    agentTitle: "Agent 6 — Le Correcteur",
    agentSubtitle: 'Qualité Éditoriale',
    agentMission: 'Contrôle cohérence, clarté, style, structure et tenue éditoriale globale.',
    agentRole: 'Sécuriser la qualité',
    agentAction: 'Contrôle qualité approfondi',
  },
  {
    id: 'P7',
    name: 'Le Packager',
    description: 'Métadonnées et mots-clés KDP optimisés',
    icon: BookOpen,
    agentTitle: "Agent 7 — Le Packager",
    agentSubtitle: 'Packaging Éditorial',
    agentMission: 'Transforme le manuscrit en offre publiable avec accroche, sous-titre et KDP pro.',
    agentRole: 'Préparer la vente',
    agentAction: 'Métadonnées et mots-clés KDP optimisés',
  },
  {
    id: 'P8',
    name: "L'Auditeur",
    description: 'Vérification cohérence globale',
    icon: AlertCircle,
    agentTitle: "Agent 8 — L'Auditeur",
    agentSubtitle: 'Diagnostic Final',
    agentMission: 'Passe le projet au scanner et détecte les failles avant validation.',
    agentRole: 'Tester la cohérence',
    agentAction: 'Vérification cohérence globale',
  },
  {
    id: 'P9',
    name: 'La Mémoire',
    description: 'Capture de VOTRE voix unique d\'auteur',
    icon: Brain,
    agentTitle: "Agent 9 — La Mémoire",
    agentSubtitle: 'Mémoire Éditoriale',
    agentMission: 'Formalise votre signature d\'auteur pour conserver une vraie cohérence de voix.',
    agentRole: 'Capturer votre voix',
    agentAction: 'Capture de VOTRE voix unique d\'auteur',
  },
  {
    id: 'P10',
    name: 'Le Relieur',
    description: 'Transitions fluides entre chapitres',
    icon: Link2,
    agentTitle: "Agent 10 — Le Relieur",
    agentSubtitle: 'Cohérence Chapitres',
    agentMission: 'Vérifie les raccords, le fil rouge et la montée en puissance du livre.',
    agentRole: 'Fluidifier les transitions',
    agentAction: 'Transitions fluides entre chapitres',
  },
  {
    id: 'P11',
    name: 'Le Critique',
    description: 'Détection des faiblesses (sans flatterie)',
    icon: ScanSearch,
    agentTitle: "Agent 11 — Le Critique",
    agentSubtitle: 'Auto-Critique',
    agentMission: 'Formule une critique franche pour identifier ce qui nuit au niveau pro.',
    agentRole: 'Pointer les faiblesses',
    agentAction: 'Détection des faiblesses (sans flatterie)',
  },
  {
    id: 'P12',
    name: 'Le Stratège',
    description: 'Améliorations automatiques',
    icon: Wand2,
    agentTitle: "Agent 12 — Le Stratège",
    agentSubtitle: 'Boucle Itérative',
    agentMission: 'Priorise les corrections et transforme la critique en actions concrètes.',
    agentRole: 'Corriger avec impact',
    agentAction: 'Améliorations automatiques',
  },
  {
    id: 'P13',
    name: 'La Signature',
    description: 'Voix d\'auteur unifiée et reconnaissable',
    icon: Award,
    agentTitle: "Agent 13 — La Signature",
    agentSubtitle: 'Signature de Style',
    agentMission: 'Harmonise le ton final pour donner une identité forte et mémorable au manuscrit.',
    agentRole: 'Unifier le style',
    agentAction: 'Voix d\'auteur unifiée et reconnaissable',
  },
  {
    id: 'P14',
    name: 'Le Jury',
    description: 'Validation finale par l\'éditeur professionnel',
    icon: BadgeCheck,
    agentTitle: "Agent 14 — Le Jury",
    agentSubtitle: 'Verdict Ultime',
    agentMission: 'Décide si le livre est publiable ou s\'il faut retravailler avant mise en vente.',
    agentRole: 'Valider la publication',
    agentAction: 'Validation finale par l\'éditeur professionnel',
  },
  {
    id: 'P15',
    name: "L'Humanisateur",
    description: '🎁 BONUS — Rend le texte indétectable par les outils anti-IA',
    icon: Shield,
    agentTitle: "Agent 15 — L'Humanisateur",
    agentSubtitle: 'Humanisation Anti-IA',
    agentMission: 'Ajoute les variations, ruptures et textures de langage qui évitent l\'effet robotique.',
    agentRole: 'Rendre le texte plus humain',
    agentAction: 'BONUS — Rend le texte indétectable par les outils anti-IA',
  },
];

export const WORKFLOW_STEP_COUNT = WORKFLOW_STEPS.length;
